### PR TITLE
Rh/toggle avatar visibility

### PR DESCRIPTION
**Pull request by rhall1705**

### CODE REVIEW

**Comment by JeffRegan** [comment]
It'd be nice if the recyclerview took an avatar factory and it was possible to pass a factory that didn't render anything.  Not sure if commenting on this pull request is the right forum for that kind of change.

**Comment by sriamar** [comment]
When sending pull requests, please do separate the changes. We always squash changes and make separate checkins per feature.

**Comment by rhall1705** [comment]
@sriamar pulled out the change from the other commit, that was my mistake. This PR should be entirely for the avatar visibility style now

**Comment by sriamar** [comment]
Hey, the changes look good. 

1. Did you test all 3 scenarios and make sure the layout is fine?
2. Please squash the 3 commits into a single commit please.

**Pull request closed without merging**
